### ISSUE TITLE
Class 'DataAttributeObserver' incorrectly implements interface 'InternalPropertyObserver'

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/binding#510]
**I'm submitting a bug report**

* **Library Version:**
1.0.5

* **Language:**
TypeScript 1.8

I got a Typescript compile error, which was introduced with 72d6675:

```
typings/modules/aurelia-binding/index.d.ts(193,14): error TS2420: Class 'DataAttributeObserver' incorrectly implements interface 'InternalPropertyObserver'.
  Property 'getValue' is missing in type 'DataAttributeObserver'.
TypeScript: 1 semantic error
```

**Comment by jdanyow** [comment]
this has been fixed in the latest version of aurelia-binding
