### PR TITLE
fix(typings, element-observation): fix typings

### LINKED ISSUE #510: Class 'DataAttributeObserver' incorrectly implements interface 'InternalPropertyObserver'
**I'm submitting a bug report**

* **Library Version:**
1.0.5

* **Language:**
TypeScript 1.8

I got a Typescript compile error, which was introduced with 72d6675:

```
typings/modules/aurelia-binding/index.d.ts(193,14): error TS2420: Class 'DataAttributeObserver' incorrectly implements interface 'InternalPropertyObserver'.
  Property 'getValue' is missing in type 'DataAttributeObserver'.
TypeScript: 1 semantic error
```

### PR DESCRIPTION
**Pull request by StrahilKazlachev**
fix #510 DataAttributeObserver typings
add (src/element-observation.js) `DataAttributeObserver.unsubscribe` for typings consistency

### CODE REVIEW

**Comment by StrahilKazlachev** [comment]
Closing as @jdanyow has already committed a fix.

**Comment by jdanyow** [comment]
@StrahilKazlachev apologies, the issue was reported to me in chat and I fixed it without checking for PRs.

**Comment by StrahilKazlachev** [comment]
@jdanyow no problem 😄 . The important for me is that tomorrow the build will be OK.
