### ISSUE TITLE
parsing of template issue: ${moment().toISOString()} does not work

### ISSUE THREAD

**Issue by bebor** [aurelia/binding#760]
this.moment = required moment

then in view:

${moment()} -- works, return date as string

${moment().toISOString()} -- does not work. no method of moment can be called, it throws error:
`moment() is not a function`

**Comment by bigopon** [comment]
@bebor can you help give a repro of the issue. As you can see from this sandbox https://codesandbox.io/s/readme-example-c1n2f

It's working fine with 1.3.1
