### ISSUE TITLE
updateTrigger error

### ISSUE THREAD

**Issue by kellyethridge** [aurelia/binding#673]
**I'm submitting a bug report**

* **Library Version:**
v1.7.0

* **Operating System:**
Windows 10

JSPM 0.16.45

* **Browser:**
all

* **Language:**
TypeScript 2.6

Hi guys,
After updating aurelia-binding to 1.7.0 my updateTrigger:'blur' behaviors have broken. Reverting back to version 1.6.0 resolves the issue.

The error I get is:
```Uncaught (in promise) TypeError: this.eventManager.createElementHandler is not a function at UpdateTriggerBindingBehavior.bind (update-trigger-binding-behavior.js:44)```

I can't recreate it in the gist because it does not seem to be using the latest version.

**Comment by Alexander-Taran** [comment]
can you still post a relevant piece of template/view-model to reproduce?

**Comment by kellyethridge** [comment]
Sure thing!

In the view:
```
<template>
<input value.bind="someValue & updateTrigger:'blur'" /> ${someValue}
</template>
```

and the view model can be simply:
```
export class App {
someValue: any;
}
```
The `updateTrigger` behavior throws an error and with the aurelia.use.developmentLogging() turned on, it is shown in the console. Remove the behavior and things work as expected.

**Comment by Alexander-Taran** [comment]
Thanks. Going to try that

**Comment by bigopon** [comment]
@Alexander-Taran @kellyethridge 

Thanks for filing this and digging into. It was my fault not scanning all of Aurelia internals that are using old behavior. Updated them in PRs . Please wait for @EisenbergEffect 

- binding: #674 
- templating-resources: aurelia/templating-resources#343

**Comment by Alexander-Taran** [comment]
@kellyethridge & @bigopon  Ok.. not going to look then (-:

**Comment by Alexander-Taran** [comment]
both PRs merged 
and libraries released
can be closed
